### ISSUE TITLE
In design_search.py , pyrobotdesign which should be imported is not found 

### ISSUE THREAD

**Issue by WhenWen** [allanzhao/RoboGrammar#1]

**Comment by allanzhao** [comment]
Could you check if `robot_design/build/examples/python_bindings` is in your PYTHONPATH?

**Comment by allanzhao** [comment]
The Python modules (pyrobotdesign, design_search) are now installed using setup.py, which should make import issues less likely in the future. Closing for now

**Comment by EtorArza** [comment]
Hei,

I also had this problem, and for me, the workaround was 

`export PYTHONPATH="$PYTHONPATH:/home/absolute/path/RoboGrammar/build/examples/python_bindings"`

where `/home/absolute/path/` is the absolute path of the RoboGrammar repo in my system. Writing this in case someone has this problem ;)
