### ISSUE TITLE
Broken Dockerfile

### ISSUE THREAD

**Issue by ThomasThelen** [allanzhao/RoboGrammar#12]
I ran into a few issues while trying to build the project using the supplied Dockerfile.

### Package Install Order
The first occurs when installing numpy-quaternion. It looks like pip isn't respecting the order of packages (I'm pretty sure pip made a change at some point, but it might be post-python 3.6)
```
 > [3/9] RUN python3 -m pip install numpy numpy-quaternion:
#6 1.830 Collecting numpy
#6 2.975   Downloading https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
#6 5.191 Collecting numpy-quaternion
#6 5.689   Downloading https://files.pythonhosted.org/packages/9c/58/d3e99c50f76aeae8aec711d2f93387d802486a4ad5c9697f0a1b48eaa018/numpy-quaternion-2022.4.1.tar.gz (59kB)
#6 6.030     Complete output from command python setup.py egg_info:
#6 6.030     Traceback (most recent call last):
#6 6.030       File "<string>", line 1, in <module>
#6 6.030       File "/tmp/pip-build-0nofek86/numpy-quaternion/setup.py", line 16, in <module>
#6 6.030         import numpy as np
#6 6.030     ModuleNotFoundError: No module named 'numpy'
```
To solve this I separated the package installation to a new line in the Dockerfile, `RUN pip3 install numpy-quaternion`, which takes advantage of _Docker_'s ordering system.

### Missing Files
The second happens when the build starts. When I inspect the contents of `/robot_design/extern/glfw` it's empty-which is probably the issue at hand. After a while I realized that I should have initialized the git submodules before building-but I think this raises a point that there's no documentation on the Docker process.
```
 > [ 8/10] RUN cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..:
#12 0.441 -- The C compiler identification is GNU 7.5.0
#12 0.604 -- The CXX compiler identification is GNU 7.5.0
#12 0.620 -- Check for working C compiler: /usr/bin/cc
#12 0.718 -- Check for working C compiler: /usr/bin/cc -- works
#12 0.722 -- Detecting C compiler ABI info
#12 0.823 -- Detecting C compiler ABI info - done
#12 0.842 -- Detecting C compile features
#12 1.148 -- Detecting C compile features - done
#12 1.162 -- Check for working CXX compiler: /usr/bin/c++
#12 1.275 -- Check for working CXX compiler: /usr/bin/c++ -- works
#12 1.276 -- Detecting CXX compiler ABI info
#12 1.396 -- Detecting CXX compiler ABI info - done
#12 1.411 -- Detecting CXX compile features
#12 1.923 -- Detecting CXX compile features - done
#12 1.940 -- Found GLEW: /usr/include (Required is at least version "1.13")
#12 1.947 -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so  found components:  OpenGL
#12 1.948 CMake Error at core/CMakeLists.txt:25 (add_subdirectory):
#12 1.948   The source directory
#12 1.948
#12 1.948     /robot_design/extern/glfw
#12 1.948
#12 1.948   does not contain a CMakeLists.txt file.
#12 1.948
#12 1.948
#12 1.949 CMake Error at core/CMakeLists.txt:34 (add_subdirectory):
#12 1.949   The source directory
#12 1.949
#12 1.949     /robot_design/extern/PEGTL
#12 1.949
#12 1.949   does not contain a CMakeLists.txt file.
#12 1.949
#12 1.949
#12 1.950 CMake Error at core/CMakeLists.txt:41 (add_subdirectory):
FROM ubuntu:18.04
#12 1.950   The source directory
#12 1.950
#12 1.950     /robot_design/extern/tinyxml2
#12 1.950
#12 1.950   does not contain a CMakeLists.txt file.
#12 1.950
#12 1.950
#12 1.951 CMake Error at examples/python_bindings/CMakeLists.txt:8 (add_subdirectory):
#12 1.951   The source directory
#12 1.951
#12 1.951     /robot_design/extern/pybind11
#12 1.951
#12 1.951   does not contain a CMakeLists.txt file.
#12 1.951
#12 1.951
#12 1.951 CMake Error at examples/python_bindings/CMakeLists.txt:9 (pybind11_add_module):
#12 1.951   Unknown CMake command "pybind11_add_module".
#12 1.951
#12 1.951
#12 1.953 -- Configuring incomplete, errors occurred!
#12 1.953 See also "/robot_design/build/CMakeFiles/CMakeOutput.log".

------
executor failed running [/bin/sh -c cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..]: exit code: 1
```

### Other Examples
Some of the other examples don't run under the provided environment (missing packages). I would expect all of the examples to work with the image. At the least, pytorch is missing from the dependencies (maybe there could be a requirements.txt)

### Provided Example
The Dockerfile, as it is now plus the fixes above, won't successfully run the example because the command line arguments are left out. I was able to copy and paste one of the examples from the main Readme and replace the line in the Dockerfile to make it run.

**Comment by allanzhao** [comment]
Thanks for letting me know, I've updated the Dockerfile and it now builds successfully on my end. I found it hard to run the graphical examples through Docker, so the direct installation is still recommended.

**Comment by ThomasThelen** [comment]
Thanks for checking it out, I really appreciate it! It should be possible to mount the local directory to the docker container so that all experiment outputs end up on the runner's computer. That way, you can still generate the research artifacts and play with the outputs
