### ISSUE TITLE
argument error when runing examples/design_search/viewer.py

### ISSUE THREAD

**Issue by GilgameshD** [allanzhao/RoboGrammar#14]
Hi, got this error when I ran the example code. Any helps or hints about it? Thanks!

Using optimization seed: 360342674
Traceback (most recent call last):
  File "examples/design_search/viewer.py", line 258, in <module>
    main()
  File "examples/design_search/viewer.py", line 156, in main
    input_sequence, result = simulate(robot, task, opt_seed, args.jobs,
  File "/home/wenhao/2_pytorch_ws/RoboGrammar/examples/design_search/design_search.py", line 124, in simulate
    value_estimator.get_observation(main_sim, obs[:,j])
TypeError: get_observation(): incompatible function arguments. The following argument types are supported:
    1. (self: pyrobotdesign.ValueEstimator, arg0: pyrobotdesign.Simulation, arg1: numpy.ndarray[float64[m, 1], flags.writeable]) -> None

Invoked with: <pyrobotdesign.NullValueEstimator object at 0x7ff6c8faf930>, <pyrobotdesign.BulletSimulation object at 0x7ff6c8f97b70>, array([], dtype=float64)

**Comment by PeideHuang** [comment]
I have exactly the same error when trying to run
`python3 examples/design_search/viewer.py RidgedTerrainTask data/designs/grammar_apr30.dot -j12 0, 7, 1, 13, 1, 2, 16, 12, 13, 6, 4, 19, 4, 17, 5, 3, 2, 16, 4, 5, 18, 9, 8, 9, 9, 8 -o`
I am using python 3.8.13 and cmake 3.16.3.

**Comment by allanzhao** [comment]
I've pushed a fix, please let me know if it still doesn't work.

(It seems like pybind11 is more strict in which array shapes it accepts now. Previously it would allow passing in an array with zero rows in that case.)

**Comment by PeideHuang** [comment]
It works as expected now. Thanks a lot!
