### ISSUE TITLE
 i wonder how to creat a task and a robot of my own , i dont even know what the numbers mean in the examples

### ISSUE THREAD

**Issue by SamSAM-WWW** [allanzhao/RoboGrammar#16]
>> i wonder how to creat a task and a robot of my own , i dont even know what the numbers means in the example

**Comment by allanzhao** [comment]
The numbers are indices into the lists of rules that can be applied at each step. This list of rules changes depending on the previous rules applied, and is very difficult to interpret. They're not really meant to be edited by hand.

It might be easier to run the design search to get more robots? This is how we got the examples in the paper.
