### ISSUE TITLE
something about Robogrammar

### ISSUE THREAD

**Issue by SamSAM-WWW** [allanzhao/RoboGrammar#17]
sorry to bother you again, but could you upload some files about the exact  meaning of  each of the numbers . Though i know that the numbers  are a sequence of grammar rules, it is quite confusing when coming to each of the certain number. No any description of the numbers. For example ,  " 0, 7, 1, 13, 1, 2, 16, 12, 13, 6, 4, 19, 4, 17, 5, 3, 2, 16, 4, 5, 18, 9, 8, 9, 9, 8 -o"  .  what means 0, what means 7?which part of the body the num represents?  how to use numbers to creat a head , a leg ? Thanks a lot .

**Comment by allanzhao** [comment]
The numbers are unfortunately not meant to be interpreted by hand, and their meaning changes depending on the previous rules applied. Automatic design search is the only intended method for creating robot designs, sorry.
