### ISSUE TITLE
pyrobotdesign

### ISSUE THREAD

**Issue by SamSAM-WWW** [allanzhao/RoboGrammar#22]
excuse me， is there a api manual for users to read？

**Comment by SamSAM-WWW** [comment]
since it's hard to get to understand the api for pyrobotdesign

**Comment by SamSAM-WWW** [comment]
Besides  is there any posiible to export to urdf or mjcf instead of obj?

**Comment by allanzhao** [comment]
Hi Sam,

This wasn't really meant as a library to include in other programs, so there isn't any API documentation unfortunately. I also don't have plans to implement any export functionality (apart from OBJ for rendering). Thanks for your interest though!
