### ISSUE TITLE
maybe some mistakes when running your tutorial

### ISSUE THREAD

**Issue by zhangzhongwd** [allanzhao/RoboGrammar#3]
1. The name of your root directory is 'RoboGrammar', not 'robot_design'.
2. When running your C++ examples, I found there was no viewer, only rule_viewer, and the file called insect.dot was in '../rl/data/designs', not '../data/designs'.
3. When I copied your command for playing python example, the terminal showed the error 'Rule in sequence has no applicable matches'.

**Comment by allanzhao** [comment]
Thanks for bringing this to my attention, I've updated the README. The Python examples now use the latest version of the grammar.
