### ISSUE TITLE
Does the graph always have a constant number of nodes?

### ISSUE THREAD

**Issue by kniranjankumar** [allanzhao/RoboGrammar#5]
From my understanding of the code, particularly preprocess.py it looks like the graph always has a constant number of nodes and a mask is used to block empty nodes. Why is this the case? Shouldnt the GNN be able to handle graphs with an arbitray number of nodes?

**Comment by allanzhao** [comment]
The graph convolutional layer we are using (DenseSAGEConv) takes in a batch of graphs as a rectangular matrix with shape `(batch_size, num_nodes, num_features)`. Only the first dimension can vary, so we just set num_nodes to some arbitrary high value. Hope this answers your question!

**Comment by kniranjankumar** [comment]
Makes Sense! Thanks!
