### ISSUE TITLE
UNABLE TO RUN SETUP.PY for PYTHON_BINDINGS

### ISSUE THREAD

**Issue by leocorp96** [allanzhao/RoboGrammar#6]
Every time I try to run this command: **_python3 examples/python_bindings/setup.py develop_**

I get this error in the terminal and I'm not exactly sure how to fix. I am of the idea that "LIBRARY_NAME" is supposed to be some sort of a placeholder but it seems nothing is being parsed to it.

**_WARNING: '${LIBRARY_NAME}' not a valid package name; please use only .-separated package names in setup.py
running develop
error: Invalid distribution name or version syntax: -LIBRARY-NAME--0.1.0_**

Please help!!

**Comment by leocorp96** [comment]
Solved it by modifying the corresponding setup.py script to this:

`import os
from setuptools import setup
os.chdir(os.path.dirname(os.path.realpath(__file__)))

inst_libs = ['py_value', 'py_sim', 'py_robot_design', 'py_robot', 'py_render', 'py_optim', 'py_graph', 'py_prop', 'py_eigen_geometry']

for lib in inst_libs:
	setup(
    name=lib,
    version='0.1.0',
    packages=[lib],
    package_dir={lib: '..'}
	)`

**Comment by EtorArza** [comment]
Hey, the code you shared has a couple of bugs. I think it is related to the formatting of GitHub. I fixed it as I was also facing this problem.

```import os
from setuptools import setup

# Change working directory to the one this file is in
os.chdir(os.path.dirname(os.path.realpath(__file__)))

inst_libs = ['py_value', 'py_sim', 'py_robot_design', 'py_robot', 'py_render', 'py_optim', 'py_graph', 'py_prop', 'py_eigen_geometry']

for lib in inst_libs:
    setup(
    name=lib,
    version='0.1.0',
    packages=[lib],
    package_dir={lib: '..'}
    )
```
