### ISSUE TITLE
ERROR WHEN RUNNING EXAMPLES

### ISSUE THREAD

**Issue by leocorp96** [allanzhao/RoboGrammar#7]
I am unable to run any of the examples due to this error.

Traceback (most recent call last):
  File "examples/design_search/viewer.py", line 2, in <module>
    from design_search import RobotDesignEnv, make_graph, build_normalized_robot, presimulate, simulate
  File "/home/ephson/RoboGrammar/examples/design_search/design_search.py", line 9, in <module>
    import pyrobotdesign as rd
ModuleNotFoundError: No module named 'pyrobotdesign'

**Comment by 1234shel** [comment]
I am getting the same error. Did you figure out a solution to this?

**Comment by leocorp96** [comment]
> I am getting the same error. Did you figure out a solution to this?

I haven't @1234shel but also I paused work on this project to focus on others. Do well to let me know if you do figure it out.

**Comment by allanzhao** [comment]
Just a wild guess: it's possible that the version of Python found by CMake isn't the same one used to run the examples, and the pyrobotdesign module will be compiled for the wrong Python version. Could you see if the Python version of the .so file in `build/examples/python_bindings/` matches the output of `python --version`? (e.g. `pyrobotdesign.cpython-36m-x86_64-linux-gnu.so` is Python 3.6)

**Comment by haoboluo** [comment]
> Just a wild guess: it's possible that the version of Python found by CMake isn't the same one used to run the examples, and the pyrobotdesign module will be compiled for the wrong Python version. Could you see if the Python version of the .so file in `build/examples/python_bindings/` matches the output of `python --version`? (e.g. `pyrobotdesign.cpython-36m-x86_64-linux-gnu.so` is Python 3.6)

Hi, thank you for your open-source code. The solution of this issue is exactly changing the python version to "3.6" and rebuilding the pyrobotdesign.
