### ISSUE TITLE
More details about  examples

### ISSUE THREAD

**Issue by Jasonleeo-cpu** [allanzhao/RoboGrammar#9]
Excuse me, I'm very interested in this project, but what has confused me for several days is the parameter details.If I want to know the parameters about the robot I have trained,how should I process the logs or where can I view the result?Hoping for your reply, thanks!

**Comment by allanzhao** [comment]
The rule sequence (rule_seq) and optimization seed (opt_seed) are the only pieces of information needed to reproduce a simulation run, besides the grammar and task name.

The command to view a particular design would then be `python3 examples/design_search/viewer.py [TaskName] data/designs/grammar_apr30.dot -j8 [rule_seq] -s [opt_seed] -o`
